### ISSUE TITLE
Use a more recent and lightweight base docker for running Postgres in local dev

### ISSUE THREAD

**Issue by madooei** [jhu-collab/proj-hourly#476]
Update the docker-compose.yml and switched the image from `postgres:13` to `postgres:15-alpine`

```yml
version: '3.9'
services:
  # Add a DB_PORT to your .env file
  #
  # To access the db in the docker
  # - DATABASE_URL=postgres://postgres:password@postgres/
  # To access the db in outside the docker
  # - DATABASE_URL=postgres://postgres:password@localhost:${DB_PORT}/

  db:
    image: postgres:15-alpine
    restart: always
    container_name: postgres-for-hourly
    ports:
      - "${DB_PORT}:5432" # HOST_PORT:CONTAINER_PORT
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

```
